server:
  port: 8781
  servlet:
    context-path: /restful-api-demo
spring:
  rocketmq:
    producer:
      group: demoGroup
alita:
#  pkGenerator:  # 雪花算法配制
#    workerId: 1  # 相同服务不同节点累加此ID
#    datacenterId: 18  # 相同服务使用相同ID, web项目从17开始,最大32
  oauth2:
    resServer:
      authPath:
        - /${spring.application.name}/mybatis-demo/**
        - /${spring.application.name}/mongo-demo/**
        - /${spring.application.name}/dataau/**
        - /${spring.application.name}/admin/**
  devHelper:
    resultCodeClassPackage: top.klw8.alita.demo.result.code  #resultCode 所在包路径,多个路径用逗号隔开