server:
  port: 8781
spring:
  rocketmq:
    producer:
      group: demoGroup
alita:
#  pkGenerator:  # 雪花算法配制
#    workerId: 1  # 相同服务不同节点累加此ID
#    datacenterId: 18  # 相同服务使用相同ID, web项目从17开始,最大32
  oauth2:
    resServer:
      authPath:
        - /demo/**
  devHelper:
    resultCodeClassPackage: top.klw8.alita.service.result.code,top.klw8.alita.service.result.code  #resultCode 所在包路径,多个路径用逗号隔开