dubbo:
  provider:
    timeout: 2000
  protocol:
    port: 20880
    name: dubbo
  scan:
    basePackages: top.klw8.alita.providers.admin.impl
  application:
    name: admin-service
#alita:
#  pkGenerator:  # 雪花算法配制
#    workerId: 1  # 相同服务不同节点累加此ID
#    datacenterId: 1  # 相同服务使用相同ID, service项目从1开始,最大16