spring:
  rocketmq:
    nameServer: 127.0.0.1:9876
  cloud: 
    nacos: 
      discovery:
        serverAddr: 127.0.0.1:8848
dubbo:
  application:
    name: restful-api-admin
  registry:
    address: nacos://127.0.0.1:8848
alita:
  redis:
    enabled: true
    defaultHost: 127.0.0.1
    defaultPort: 6379