spring:
  cloud: 
    nacos: 
      discovery:
        serverAddr: 127.0.0.1:8848
dubbo:
  application:
    name: restful-api-authorization
  registry:
    address: nacos://127.0.0.1:8848
alita:
  redis:
    enabled: true
    defaultHost: 127.0.0.1
    defaultPort: 6379
    extendHosts[0]: 127.0.0.1
    extendPorts[0]: 6379
    extendBeanIds[0]: redisTest1Template
  oauth2:
    clients:
      clientList:
        - clientId: alita_test
          clientSecret: $2a$10$9s0p62wfKh7WT64a/VYFpOAk19GsrHh5C7Ty9.wPRWX40cjq7Rmu.
          scope:
            - select
          authorizedGrantTypes:
            - refresh_token
            - password
            - sms_code
          authorities:
            - client